[package]
name = "wfcgen"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
edition = "2018"
repository = "https://github.com/rickyhan/fastwfc-rs"
description = "Rust bindings to libfastwfc"
license = "MIT"

[dependencies]
fastwfc = "0.1.0"
image = "0.22.3"
structopt = "0.3.0"
